# Generated by Django 4.2.20 on 2025-05-22 14:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facial_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnknownFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='unknown_faces/')),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed', models.BooleanField(default=False)),
                ('encoding', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='face',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='face',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='face',
            name='identifier',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='face',
            name='surname',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='face',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
